import {standardize,percent,points} from './math.js';
import {loadState,saveState,toggleId,searchLessons} from './state.js';
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={book:'<path d="M12 5c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Zm0 0v15"/>',lab:'<path d="M8 3h8M10 3v7L4 20h16l-6-10V3M8 14h8"/>',bookmark:'<path d="M6 3h12v18l-6-4-6 4Z"/>',check:'<path d="m5 12 4 4L19 6"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',chevron:'<path d="m9 5 7 7-7 7"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-11v1"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.book}</svg>`;
const statusNames={outline:'学习提纲',draft:'草稿',demo:'原创示例',ready:'可学习'};
let catalog,lessons,lessonMap,state,storageWorks=true,currentRoute='',toastTimer;
let activeLesson=null;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600);}
function persist(){try{storageWorks=saveState(window.localStorage,state);}catch{storageWorks=false;}if(!storageWorks)toast('浏览器未允许保存，当前记录仅在本次打开期间保留。');}
function badge(l){return `<span class="status status-${esc(l.status)}">${statusNames[l.status]}</span>`;}
function chapterLabel(n){return `第 ${String(n).padStart(2,'0')} 周`;}
const lessonUrl=id=>`#/lesson/${id}`;
function sidebarHtml(){
 const on=currentRoute.startsWith('/lesson/')?activeLesson?.week:Number(currentRoute.split('/week/w')[1]);
 const completed=state.completed.filter(id=>lessonMap.get(id)?.status!=='outline').length;
 return `<a class="brand" href="#/" aria-label="因果推断学习笔记首页"><span class="brand-mark"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="m10 30 10-20 10 20M10 30h20"/><circle cx="20" cy="10" r="3"/><circle cx="10" cy="30" r="3"/><circle cx="30" cy="30" r="3"/></svg></span><span><strong>因果推断</strong><small>CAUSAL STUDY NOTES</small></span></a>
 <div class="side-scroll"><p class="nav-label">学习空间</p><nav class="primary-nav"><a href="#/" ${currentRoute==='/'?'aria-current="page"':''}>${icon('book')}课程目录<span class="nav-count">39</span></a><a href="#/lab/standardization" ${currentRoute.startsWith('/lab')?'aria-current="page"':''}>${icon('lab')}互动实验</a><a href="#/saved" ${currentRoute==='/saved'?'aria-current="page"':''}>${icon('bookmark')}学习记录</a></nav>
 <div class="nav-label chapter-nav-label"><span>九周学习路径</span><span>01—09</span></div><nav class="chapter-nav">${catalog.weeks.map(w=>`<a href="#/week/${w.id}" ${on===w.number?'aria-current="page"':''}><span>${String(w.number).padStart(2,'0')}</span><b>${esc(w.title)}</b></a>`).join('')}</nav>
 <div class="side-bottom"><a href="#/guide">${icon('info')}使用说明</a><div class="progress-heading"><span>我的学习进度</span><strong>${completed}<small> / 39</small></strong></div><div class="progress-track"><span style="width:${completed/39*100}%"></span></div><p>记录保存在当前浏览器</p></div></div>`;
}
function updateSidebar(){const html=sidebarHtml();$('#sidebar').innerHTML=html;$('#mobile-nav-content').innerHTML=html;}
function dagSvg(){return `<svg class="dag-graphic" viewBox="0 0 410 230" role="img" aria-labelledby="dag-title"><title id="dag-title">共同原因 W 同时影响处理 A 和结局 Y；A 指向 Y。</title><defs><marker id="arrow-dag" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="m0 0 10 5-10 5" fill="none" stroke="currentColor" stroke-width="1.5"/></marker></defs><g fill="none" stroke="#b7a494" stroke-width="1.5" marker-end="url(#arrow-dag)"><path d="M183 80 109 153"/><path d="m228 80 74 73"/><path d="M128 176h153"/></g><g fill="#fffdf8" stroke="#c9bbae" stroke-width="1.5"><circle cx="205" cy="54" r="35"/><circle cx="90" cy="178" r="35"/><circle cx="320" cy="178" r="35"/></g><g text-anchor="middle" fill="#7b2939" font-family="Georgia,serif" font-style="italic" font-size="28"><text x="205" y="64">W</text><text x="90" y="188">A</text><text x="320" y="188">Y</text></g><g fill="#7e756e" font-size="10" text-anchor="middle"><text x="266" y="56">基线特征</text><text x="90" y="231">处理</text><text x="320" y="231">结局</text><text x="205" y="165">处理效应</text></g></svg>`;}
function lessonRow(l){const done=state.completed.includes(l.id),saved=state.bookmarks.includes(l.id);return `<a href="${lessonUrl(l.id)}" class="lesson-row"><span class="lesson-number">${String(l.order).padStart(2,'0')}</span><span class="lesson-row-copy"><strong>${esc(l.title)}</strong><small>${esc(l.summary)}</small></span>${done?icon('check','done-icon'):saved?icon('bookmark','saved-icon'):''}${badge(l)}${icon('chevron','row-chevron')}</a>`;}
function weekCard(w,open=false){return `<details class="week-card" ${open?'open':''} id="${w.id}"><summary><span class="week-number">${String(w.number).padStart(2,'0')}</span><span class="week-heading"><strong>${esc(w.title)}</strong><small>${esc(w.summary)}</small></span><span class="week-count">${w.lessons.length} 节</span>${icon('chevron','week-chevron')}</summary><div class="week-lessons">${w.lessons.map(id=>lessonRow(lessonMap.get(id))).join('')}</div></details>`;}
function heading(kicker,title,description,aside=''){return `<div class="page-heading"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${description}</p></div>${aside}</div>`;}
function home(){const readable=lessons.filter(l=>l.status!=='outline');const last=lessonMap.get(state.lastLesson);return `${heading('CAUSAL INFERENCE · STUDY NOTES','因果推断学习笔记','研究问题、识别条件、估计方法与结果解释。',`<div class="edition">${esc(catalog.edition)}</div>`)}
 <section class="feature"><div class="feature-copy"><span class="eyebrow">学习路线</span><h2>从研究问题出发<br>理解因果效应估计</h2><p>依次学习潜在结果、混杂控制和标准化，再进入机器学习、双重稳健与拓展应用。</p><div class="feature-links"><a class="button" href="${lessonUrl(last&&last.status!=='outline'?last.id:'w01-l01')}">${last&&last.status!=='outline'?'继续上次阅读':'从第一节开始'}</a><a class="text-link" href="#/guide">使用说明</a></div><div class="feature-meta"><span><b>9</b> 周目录</span><span><b>39</b> 节结构</span><span><b>${readable.length}</b> 节已编写正文</span></div></div><div class="feature-diagram"><div class="figure-topline"><span>有向无环图 · DAG</span><span class="mini-label">原创示意</span></div>${dagSvg()}<p>先说明变量关系，再确定调整策略。</p></div></section>
 <div class="build-notice">${icon('info')}<p>39 节正文均可阅读。示例采用合成数据；代码执行状态逐块标注，阅读标记与自测答案仅保存在当前浏览器。</p></div>
 <section aria-labelledby="curriculum-title"><div class="section-heading"><div><span class="eyebrow">CURRICULUM</span><h2 id="curriculum-title">九周学习目录</h2></div><button class="text-button" id="toggle-weeks">展开全部</button></div><div class="curriculum">${catalog.weeks.map(w=>weekCard(w,w.number===1)).join('')}</div></section>
 <section class="bottom-pair"><a href="#/lab/standardization" class="lab-teaser"><span class="teaser-icon">${icon('lab')}</span><span><small>合成数据 · 交互示例</small><strong>目标人群与标准化</strong><p>调整人群构成，观察粗比较与标准化风险。</p></span></a><div class="reading-note"><h3>每节学习的三个检查点</h3><p><span>01</span> 明确目标人群和效果尺度</p><p><span>02</span> 列出识别条件与支持范围</p><p><span>03</span> 核对估计、诊断和不确定性</p></div></section>`;}
function weekPage(id){const w=catalog.weeks.find(w=>w.id===id);if(!w)return notFound();return `${heading(`WEEK ${String(w.number).padStart(2,'0')} · ${w.phase}`,esc(w.title),esc(w.summary))}<div class="week-intro"><span>先修知识</span><p>${esc(w.prerequisites)}</p></div><section class="week-page-list" aria-label="本周课程">${w.lessons.map(id=>lessonRow(lessonMap.get(id))).join('')}</section><div class="page-nav"><a href="#/">← 返回课程目录</a>${catalog.weeks[w.number]?`<a href="#/week/${catalog.weeks[w.number].id}">下一周 </a>`:''}</div>`;}
function safeMathML(markup,fallback){
 if(!markup)return `<span class="formula-fallback">${esc(fallback)}</span>`;
 const allowed=new Set(['math','mrow','mi','mn','mo','msub','msup','msubsup','mfrac','msqrt','mroot','mtext','munder','mover','munderover','mtable','mtr','mtd','mfenced','mspace']);
 const attributes=new Set(['xmlns','display','mathvariant','stretchy','fence','separator','open','close','separators','columnalign','rowspacing','columnspacing','width','height','depth','lspace','rspace']);
 const doc=new DOMParser().parseFromString(markup,'application/xml');
 if(doc.querySelector('parsererror')||doc.documentElement.localName!=='math')return `<span class="formula-fallback">${esc(fallback)}</span>`;
 for(const el of [doc.documentElement,...doc.documentElement.querySelectorAll('*')]){
  if(!allowed.has(el.localName))return `<span class="formula-fallback">${esc(fallback)}</span>`;
  for(const a of [...el.attributes])if(!attributes.has(a.name))el.removeAttribute(a.name);
 }
 doc.documentElement.setAttribute('aria-label',fallback);
 return new XMLSerializer().serializeToString(doc.documentElement);
}
function blockHtml(b){
 if(b.type==='paragraph')return `<p>${esc(b.text)}</p>`;
 if(b.type==='list'){const t=b.ordered?'ol':'ul';return `<${t}>${b.items.map(t=>`<li>${esc(t)}</li>`).join('')}</${t}>`;}
 if(b.type==='callout')return `<aside class="callout ${b.tone==='warning'?'warning':''}"><strong>${esc(b.title)}</strong><p>${esc(b.text)}</p></aside>`;
 if(b.type==='equation')return `<figure class="equation">${safeMathML(b.mathml,b.text)}${b.caption?`<figcaption>${esc(b.caption)}</figcaption>`:''}</figure>`;
 if(b.type==='table')return `<figure class="data-table"><div class="table-scroll" tabindex="0" aria-label="可横向滚动的数据表"><table><thead><tr>${b.headers.map(t=>`<th scope="col">${esc(t)}</th>`).join('')}</tr></thead><tbody>${b.rows.map(row=>`<tr>${row.map((v,i)=>i===0?`<th scope="row">${esc(v)}</th>`:`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${b.caption?`<figcaption>${esc(b.caption)}</figcaption>`:''}</figure>`;
 if(b.type==='code')return `<figure class="code-block"><div class="code-header"><span>${esc(b.language)} <small>${b.execution==='verified'?'已运行核验':'尚未运行'}</small></span><button class="copy-code" aria-label="复制代码">${icon('copy')}复制</button></div><pre tabindex="0"><code>${esc(b.code)}</code></pre>${b.caption?`<figcaption>${esc(b.caption)}</figcaption>`:''}</figure>`;
 if(b.type==='exercise')return exerciseHtml(b);
 if(b.type==='interactive'&&b.kind==='standardization')return labHtml();
 if(b.type==='diagram'&&b.kind==='confounding-dag')return `<figure class="article-dag">${dagSvg()}${b.caption?`<figcaption>${esc(b.caption)}</figcaption>`:''}</figure>`;
 return '';
}
function exerciseHtml(b){const answered=Object.hasOwn(state.answers,b.id),selected=state.answers[b.id];return `<form class="exercise" data-exercise="${esc(b.id)}"><span class="eyebrow">SELF CHECK · 自测</span><fieldset><legend>${esc(b.prompt)}</legend>${b.options.map((o,i)=>`<label class="answer-option"><input type="radio" name="${esc(b.id)}" value="${i}" ${selected===i?'checked':''}><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></label>`).join('')}</fieldset><button type="submit" class="button small">检查答案</button><div class="answer-feedback ${answered?(selected===b.answer?'correct':'incorrect'):''}" role="status" ${answered?'':'hidden'}>${answered?`<strong>${selected===b.answer?'回答正确':'再想一想'}</strong><p>${esc(b.explanation)}</p>`:''}</div></form>`;}
function labHtml(){return `<section class="standardization-lab" data-lab="standardization" aria-label="目标人群标准化实验"><div class="lab-heading"><div><span class="eyebrow">INTERACTIVE LAB</span><h3>改变目标人群的构成</h3></div><span class="mini-label">合成数据</span></div><p class="lab-intro">固定两层内的风险，只改变高基线风险层在目标人群中的比例。</p><div class="lab-control"><label>目标人群中高风险层占比 <output data-target-output>50%</output><input data-target type="range" min="0" max="100" value="50" step="5" aria-label="目标人群中高风险层占比" aria-valuetext="50%"></label><div class="range-labels"><span>0%</span><span>50%</span><span>100%</span></div></div><div class="risk-bars"><div class="risk-row"><span>全部设为 A = 0</span><div class="bar-track"><div class="risk-bar untreated" data-bar0></div></div><output data-mu0>24.0%</output></div><div class="risk-row"><span>全部设为 A = 1</span><div class="bar-track"><div class="risk-bar treated" data-bar1></div></div><output data-mu1>17.0%</output></div><div class="bar-axis"><span>0%</span><span>20%</span><span>40%</span></div></div><div class="lab-results"><div><span>标准化风险差</span><strong data-rd>−7.0</strong><small>个百分点</small></div><div><span>原始两组粗风险差</span><strong class="muted-result" data-crude>+5.6</strong><small>个百分点 · 构成固定</small></div></div><p class="lab-explanation" data-explanation></p><details class="lab-details"><summary>查看本例设定与计算</summary><p>低风险层：Q₀ = 0.12，Q₁ = 0.08；高风险层：Q₀ = 0.36，Q₁ = 0.26。原始处理组高风险占 80%，未处理组占 20%。</p><p data-calculation></p><p>这些是自行设定的教学概率。交互不生成样本或置信区间；因果解释另外依赖一致性、条件交换性和正性。</p></details><button class="text-button lab-reset" type="button">重置到 50%</button></section>`;}
function updateLab(root){const input=$('[data-target]',root),p=Number(input.value)/100,r=standardize(p);$('[data-target-output]',root).textContent=percent(p,0);input.setAttribute('aria-valuetext',percent(p,0));$('[data-bar0]',root).style.width=`${r.mu0/.4*100}%`;$('[data-bar1]',root).style.width=`${r.mu1/.4*100}%`;$('[data-mu0]',root).textContent=percent(r.mu0);$('[data-mu1]',root).textContent=percent(r.mu1);$('[data-rd]',root).textContent=points(r.rd).replace('-','−');$('[data-crude]',root).textContent=points(r.crudeRd);$('[data-explanation]',root).textContent=`在这个目标人群中，标准化风险由 ${percent(r.mu0)} 降至 ${percent(r.mu1)}，相差 ${Math.abs(r.rd*100).toFixed(1)} 个百分点。两种干预使用相同的人群权重。`;$('[data-calculation]',root).textContent=`E[Y(0)] = ${(1-p).toFixed(2)} × 0.12 + ${p.toFixed(2)} × 0.36 = ${r.mu0.toFixed(3)}；E[Y(1)] = ${(1-p).toFixed(2)} × 0.08 + ${p.toFixed(2)} × 0.26 = ${r.mu1.toFixed(3)}。`;}
function lessonPage(id){const l=lessonMap.get(id);if(!l)return notFound();activeLesson=l;state.lastLesson=l.id;persist();const w=catalog.weeks[l.week-1],index=lessons.findIndex(x=>x.id===id);return `<header class="lesson-heading"><div class="lesson-kicker"><a href="#/week/${w.id}">${chapterLabel(l.week)}</a><span>/</span><span>第 ${l.order} 节</span>${badge(l)}</div><h1>${esc(l.title)}</h1><p>${esc(l.summary)}</p><div class="lesson-tools">${l.readingMinutes?`<span>约 ${l.readingMinutes} 分钟阅读</span>`:''}<button data-bookmark="${l.id}" aria-pressed="${state.bookmarks.includes(l.id)}">${icon('bookmark')}<span>${state.bookmarks.includes(l.id)?'已收藏':'收藏本节'}</span></button><button data-complete="${l.id}" ${l.status==='outline'?'disabled':''} aria-pressed="${state.completed.includes(l.id)}">${icon('check')}<span>${state.completed.includes(l.id)?'已读完':'标记已读完'}</span></button></div></header>
 <div class="lesson-layout"><article class="article ${l.status==='outline'?'outline-article':''}">${l.statusNote?`<div class="editorial-note">${esc(l.statusNote)}</div>`:''}${l.status==='outline'?`<div class="outline-icon">${icon('book')}</div><span class="eyebrow">LESSON OUTLINE</span><h2>本节学习范围</h2><p>本节正文仍在编写与核验。目前可以查看主题提纲，或收藏后继续阅读其他内容。</p><ul class="topic-list">${l.tags.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><a href="${lessonUrl('w02-l04')}" class="button secondary">阅读标准化示例 </a>`:`${l.objectives.length?`<section class="objectives"><span class="eyebrow">学习目标</span><ul>${l.objectives.map(o=>`<li>${esc(o)}</li>`).join('')}</ul></section>`:''}${l.sections.map((s,i)=>`<section class="reading-section" id="section-${esc(s.id)}"><div class="section-index">${String(i+1).padStart(2,'0')}</div><h2>${esc(s.title)}</h2>${s.blocks.map(blockHtml).join('')}</section>`).join('')}${l.references.length?`<section class="references" id="section-references"><h2>参考来源</h2><ol>${l.references.map(r=>`<li><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)}</a><p>${esc(r.authors)} · ${esc(r.year)} · ${esc(r.locator)}</p></li>`).join('')}</ol><p class="source-disclaimer">本站文字、数字、代码与图形为独立组织的学习材料。参考文献用于说明方法来源。</p></section>`:''}`}</article><aside class="lesson-aside">${l.sections.length?`<nav class="lesson-toc" aria-label="本节目录"><span class="eyebrow">本节内容</span>${l.sections.map((s,i)=>`<button data-section="section-${esc(s.id)}"><small>${String(i+1).padStart(2,'0')}</small>${esc(s.title)}</button>`).join('')}${l.references.length?'<button data-section="section-references"><small>↗</small>参考来源</button>':''}</nav>`:''}<div class="aside-note"><span class="eyebrow">学习提示</span><p>先写清目标量，再检查假设、数据与估计步骤。</p><div class="aside-rule"></div><small>学习记录仅保存在当前浏览器。清除网站数据会删除记录。</small></div></aside></div><div class="page-nav lesson-page-nav">${index>0?`<a href="${lessonUrl(lessons[index-1].id)}"><small>上一节</small><span>← ${esc(lessons[index-1].title)}</span></a>`:'<span></span>'}${index<lessons.length-1?`<a href="${lessonUrl(lessons[index+1].id)}"><small>下一节</small><span>${esc(lessons[index+1].title)} →</span></a>`:''}</div>`;}
function labPage(){return `${heading('INTERACTIVE LAB · 01','目标人群与标准化','用两层合成人群，比较原始两组风险与同一目标人群下的风险。')}<div class="standalone-lab">${labHtml()}<aside><h2>实验中的固定量</h2><p>两层内的处理和未处理风险保持固定。拖动滑块只改变目标人群的权重。</p><p>原始两组有不同的风险层构成，因此粗比较可能与标准化后的方向不同。</p><div class="callout"><strong>解释边界</strong><p>算术演示本身不能证明交换性。真实研究还需结合设计、时间顺序和领域知识判断识别条件。</p></div><a class="text-link" href="${lessonUrl('w02-l04')}">阅读推导与练习 </a></aside></div>`;}
function savedPage(){const saved=lessons.filter(l=>state.bookmarks.includes(l.id)),done=lessons.filter(l=>state.completed.includes(l.id)&&l.status!=='outline');return `${heading('MY STUDY','学习记录','收藏与阅读进度保存在当前浏览器，不需要登录。')}<div class="study-stats"><div><strong>${done.length}<small> / 39</small></strong><span>已读完</span></div><div><strong>${saved.length}</strong><span>已收藏</span></div><div><strong>${Object.keys(state.answers).length}</strong><span>已回答自测</span></div></div><section><div class="section-heading"><h2>我的收藏</h2></div>${saved.length?`<div class="week-page-list">${saved.map(lessonRow).join('')}</div>`:'<div class="empty-state">'+icon('bookmark')+'<h3>还没有收藏</h3><p>打开一节课程，选择收藏本节，即可在这里继续阅读。</p><a href="#/" class="text-link">浏览课程目录</a></div>'}</section><section><div class="section-heading"><h2>已读完</h2></div>${done.length?`<div class="week-page-list">${done.map(lessonRow).join('')}</div>`:'<p class="muted">读完正文后，可以在课程标题下方标记完成。</p>'}</section><div class="build-notice">${icon('info')}<p>这些记录仅反映个人阅读操作。标记完成不代表已掌握知识，也不会改变课程正文的编写状态。</p></div>`;}
function guidePage(){return `${heading('READING GUIDE','使用说明','内容状态、学习顺序与记录方式。')}<article class="article guide-article"><section class="reading-section"><h2>当前版本</h2><p>网站按九周、39 节组织学习内容，当前有 ${lessons.filter(l=>l.status==='ready').length} 节可学习正文，包含方法推导、原创例子、代码和带解释的自测题。</p><p>目录按自学阅读顺序组织。可以从基础概念依次学习，也可以搜索研究中遇到的方法，再补读所需前置知识。</p><div class="status-guide"><p><span class="status status-ready">可学习</span> 正文与引用已完成相应核验，代码执行状态另行标注。</p><p>18 个 Python 示例已执行检查；65 个 R 示例完成静态检查，尚未实际运行。运行前请确认依赖、输入和软件版本。</p></div></section><section class="reading-section"><h2>建议的学习方式</h2><ol><li>先明确本节的研究目标、记号和识别条件。</li><li>阅读推导，再改变实验参数检查自己的理解。</li><li>完成自测，核对解释，再运行标注为尚未运行的代码。</li><li>用自己的研究问题复述目标人群、处理、结局和时间窗。</li></ol></section><section class="reading-section"><h2>本地记录与隐私</h2><p>收藏、阅读标记和自测答案使用当前浏览器的本地存储。网站不上传这些数据，不设置账号，不加载分析追踪服务。</p><p>更换设备或浏览器不会同步记录。隐私浏览、浏览器限制或清除网站数据可能使记录丢失。</p></section><section class="reading-section"><h2>材料与数值的边界</h2><p>网站只提供独立撰写的文字、推导、图形、代码和合成例子，并列出相关公开学术来源。课程原始视频、音频、讲义、转录和研究个体数据不在本站提供。</p><p>合成例子的数字只用于演示方法。代码是否实际执行会单独标注；代码出现在页面上并不代表它已经运行。本站内容不构成医疗建议或真实研究结论。</p></section></article>`;}
function notFound(){return `<div class="empty-state not-found"><span class="eyebrow">404</span><h1>没有找到这页内容</h1><p>请从目录重新选择一节课程。</p><a class="button" href="#/">返回课程目录</a></div>`;}
function route(){
 currentRoute=location.hash.replace(/^#/,'')||'/';activeLesson=null;
 let html,title='课程目录';
 if(currentRoute==='/')html=home();else if(/^\/week\/w0[1-9]$/.test(currentRoute)){const id=currentRoute.split('/')[2];html=weekPage(id);title=catalog.weeks.find(w=>w.id===id)?.title||'课程目录';}
 else if(/^\/lesson\/w0[1-9]-l\d{2}$/.test(currentRoute)){const id=currentRoute.split('/')[2];html=lessonPage(id);title=lessonMap.get(id)?.title||'未找到课程';}
 else if(currentRoute==='/lab/standardization'){html=labPage();title='互动实验';}
 else if(currentRoute==='/saved'){html=savedPage();title='学习记录';}
 else if(currentRoute==='/guide'){html=guidePage();title='使用说明';}else{html=notFound();title='未找到页面';}
 $('#main').innerHTML=html;$('#breadcrumb').innerHTML=`<a href="#/">学习空间</a><span>/</span><b>${esc(title)}</b>`;document.title=`${title} · 因果推断学习笔记`;updateSidebar();bindPage();
 $$('dialog[open]').forEach(d=>d.close());window.scrollTo(0,0);$('#main').focus({preventScroll:true});
}
function bindPage(){
 $$('[data-lab]').forEach(root=>{updateLab(root);$('[data-target]',root).addEventListener('input',()=>updateLab(root));$('.lab-reset',root).addEventListener('click',()=>{$('[data-target]',root).value=50;updateLab(root);});});
 $('#toggle-weeks')?.addEventListener('click',e=>{const cards=$$('.week-card'),open=cards.some(c=>!c.open);cards.forEach(c=>c.open=open);e.currentTarget.textContent=open?'收起全部':'展开全部';});
 $$('[data-bookmark]').forEach(b=>b.addEventListener('click',()=>{state.bookmarks=toggleId(state.bookmarks,b.dataset.bookmark);persist();const yes=state.bookmarks.includes(b.dataset.bookmark);b.setAttribute('aria-pressed',yes);$('span',b).textContent=yes?'已收藏':'收藏本节';updateSidebar();toast(yes?'已加入收藏':'已取消收藏');}));
 $$('[data-complete]').forEach(b=>b.addEventListener('click',()=>{if(b.disabled)return;state.completed=toggleId(state.completed,b.dataset.complete);persist();const yes=state.completed.includes(b.dataset.complete);b.setAttribute('aria-pressed',yes);$('span',b).textContent=yes?'已读完':'标记已读完';updateSidebar();toast(yes?'已保存阅读进度':'已取消完成标记');}));
 $$('[data-section]').forEach(b=>b.addEventListener('click',()=>{const target=document.getElementById(b.dataset.section);target?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}));
 $$('.copy-code').forEach(b=>b.addEventListener('click',async()=>{const code=$('code',b.closest('.code-block')).textContent;try{await navigator.clipboard.writeText(code);toast('代码已复制');}catch{const range=document.createRange();range.selectNodeContents($('code',b.closest('.code-block')));const s=getSelection();s.removeAllRanges();s.addRange(range);toast('代码已选中，请使用系统复制快捷键。');}}));
 $$('[data-exercise]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const id=form.dataset.exercise,selected=$('input:checked',form),block=activeLesson?.sections.flatMap(s=>s.blocks).find(b=>b.type==='exercise'&&b.id===id),feedback=$('.answer-feedback',form);if(!selected){feedback.hidden=false;feedback.className='answer-feedback';feedback.textContent='请先选择一个答案。';return;}if(!block)return;const value=Number(selected.value);state.answers[id]=value;persist();feedback.hidden=false;feedback.className=`answer-feedback ${value===block.answer?'correct':'incorrect'}`;feedback.innerHTML=`<strong>${value===block.answer?'回答正确':'再想一想'}</strong><p>${esc(block.explanation)}</p>`;}));
}
function openSearch(){const d=$('#search-dialog');if(!d.open)d.showModal();$('#search-input').focus();}
function search(){const q=$('#search-input').value,results=searchLessons(lessons,q);$('#search-count').textContent=q.trim()?`找到 ${results.length} 节课程`:'按课程名称、关键词和已编写内容搜索';$('#search-results').innerHTML=results.length?results.map(l=>`<a href="${lessonUrl(l.id)}" class="search-result"><span>${chapterLabel(l.week)} · 第 ${l.order} 节</span><strong>${esc(l.title)}</strong><p>${esc(l.summary)}</p>${badge(l)}</a>`).join(''):q.trim()?'<div class="search-empty">暂时没有匹配内容。可以尝试更短的关键词，例如 AIPW。</div>':'';}
async function start(){try{const response=await fetch('./content/course.json');if(!response.ok)throw new Error('Content unavailable');const data=await response.json();catalog=data.catalog;lessons=data.lessons;lessonMap=new Map(lessons.map(l=>[l.id,l]));let storage;try{storage=window.localStorage;}catch{storage=null;}const loaded=loadState(storage,lessons.map(l=>l.id));state=loaded.state;storageWorks=loaded.persisted;
 $('.skip-link').addEventListener('click',e=>{e.preventDefault();$('#main').focus();$('#main').scrollIntoView({block:'start'});});
 $('#search-button').innerHTML=`${icon('search')}<span>搜索课程与概念</span><kbd>/</kbd>`;$('#search-button').addEventListener('click',openSearch);$('#search-input').addEventListener('input',search);$('#menu-button').addEventListener('click',()=>$('#mobile-nav').showModal());$$('[data-close]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.close).close()));$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){const d=$('dialog[open]');if(d){e.preventDefault();d.close();}return;}if(e.key==='/'&&!/input|textarea|select/i.test(e.target.tagName)&&!e.target.isContentEditable){e.preventDefault();if(!$('#mobile-nav').open)openSearch();}});document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#/"]');if(a){$$('dialog[open]').forEach(d=>d.close());if(a.getAttribute('href')===location.hash)route();}});window.addEventListener('hashchange',route);route();if(!storageWorks)toast('本地记录暂不可用，仍可正常阅读课程。');
 }catch(error){$('#main').innerHTML='<div class="empty-state"><h1>学习目录暂时未能载入</h1><p>请确认通过 HTTP 服务打开网站，并重新载入页面。</p><button class="button" id="retry">重新载入</button></div>';$('#retry').addEventListener('click',()=>location.reload());console.error(error);}}
start();
